services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: the-diamond-scheduler
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d the-diamond-scheduler"]
      interval: 2s
      timeout: 2s
      retries: 20

  api:
    build: ./api
    env_file: .env
    ports: ["8080:8080"]
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/healthcheck || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  dbdata:

