# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: ['**']     # all branches
  pull_request:
    branches: ['main']   # PRs targeting main

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: scheduler/api

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true
          cache-dependency-path: scheduler/api/go.sum

      - name: Ensure modules are tidy
        run: go mod tidy

      - name: Run tests
        run: go test ./... -race -v
